In this analysis, we set out to create a Top 25 Billboard-style ranking for the popularity of Reddit's subreddits, where popularity is defined by the number of posts made to a given subreddit. While it would have been simplest to prescribe the period of comparison (e.g. month over month, hour over hour), the best user experience comes when you grant the user the power to decide at what level they want to measure, and which particular periods they want to compare. To enable this decision, we allow the user to define the variable `grp` and three subsequent moments in time (i, j, k), thus dictating which time periods will be compared throughout the rest of the analysis.

To calculate the change in subreddit ranking period over period, we first group and count subreddit posts at the level previously defined by the user. Then, we sort and create a ranking column on each period's dataframe to reflect current standings. We join the datasets by subreddit and use the ranking colums to calculate change, then we join the result back to that of the period we are interested in to create the final table: the top 25 subreddits for a given time period, and the change in ranking since the last measure (+, -, or NA if the subreddit is new to the top 25). This process is repeated twice, so the user can view change over two periods without having to make further adjustments to the code.

Because Reddit hosts millions of posts, and given that the user is able to define a period of up to a month for the analysis, the code is run with the help of `SparkR`. This improves run time and gives the user the option to connect to remotely hosted data (provided they have the resources to get it there in the first place!)

```{r}
load("subreddits.Rdata")
res_i
res_j
res_k
```
